### ISSUE TITLE
(Feature) Inital version of the web app

### ISSUE THREAD

**Issue by dusan-turajlic** [TurkuForge/baby-project-web#4]
## Detailed Description

Create an initial version of the application with the following features

- [ ] Can connect to the API endpoint
- [ ] Can display all the channels the API provides
- [ ] Can open and subscribe to a single channels endpoint
- [ ] Can send and receive messages

## Context

So we can start testing the app and figure out if there are any obeys flaws in our architecture.
